### ISSUE TITLE
color-string 1.0.0 introduces breaking changes

### ISSUE THREAD

**Issue by pgoldrbx** [stoyan/csscolormin#2]
the current semver of `*` allows any update from `color-min` including breaking changes recently released:
https://github.com/Qix-/color-string/compare/0.4.0...1.0.1

**Comment by fhemberger** [comment]
Can you please push this change to npm? It currently breaks cssshrink.

```
node_modules/gulp-cssshrink/node_modules/cssshrink/node_modules/csscolormin/index.js:31
      .rgbaString(rgb, alpha)
       ^

TypeError: string.rgbaString is not a function
```
